---
deployment:
  tasks:
    # 1. Definir caminho de deploy
    - export DEPLOYPATH=/home1/abdonc73/iagus.com.br

    # 2. Copiar todos os arquivos do repo para o DEPLOYPATH
    - /bin/cp -R . $DEPLOYPATH

    # 3. Instalar dependências PHP (sem dev, otimizado)
    - cd $DEPLOYPATH && /usr/local/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction 2>&1

    # 4. Limpar caches antigos
    - cd $DEPLOYPATH && /usr/local/bin/php artisan optimize:clear 2>&1

    # 5. Rodar migrations (--force para produção)
    - cd $DEPLOYPATH && /usr/local/bin/php artisan migrate --force 2>&1

    # 6. Cache de produção (config, routes, views)
    - cd $DEPLOYPATH && /usr/local/bin/php artisan optimize 2>&1

    # 7. Criar symlink de storage (se não existir)
    - cd $DEPLOYPATH && /usr/local/bin/php artisan storage:link --relative 2>&1

    # 8. Permissões de escrita para storage e cache
    - chmod -R 775 $DEPLOYPATH/storage
    - chmod -R 775 $DEPLOYPATH/bootstrap/cache
