---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/abdonc73/iagus.com.br

    # 1. Copiar arquivos do repo para o site
    - /bin/cp -R . $DEPLOYPATH

    # 2. Localizar o PHP correto
    - export PHP_BIN=$(which php84 || which php83 || which php 2>/dev/null | head -1)
    - echo "PHP encontrado em: $PHP_BIN"
    - $PHP_BIN -v

    # 3. Localizar ou baixar o Composer
    - export COMPOSER_BIN=$(which composer 2>/dev/null || echo "")
    - if [ -z "$COMPOSER_BIN" ] && [ -f "/usr/local/bin/composer" ]; then export COMPOSER_BIN=/usr/local/bin/composer; fi
    - if [ -z "$COMPOSER_BIN" ] && [ -f "/usr/bin/composer" ]; then export COMPOSER_BIN=/usr/bin/composer; fi
    - if [ -z "$COMPOSER_BIN" ]; then echo "Baixando composer.phar..."; curl -sS https://getcomposer.org/installer | $PHP_BIN -- --install-dir=/tmp --filename=composer; export COMPOSER_BIN=/tmp/composer; fi
    - echo "Composer encontrado em: $COMPOSER_BIN"

    # 4. Instalar dependencias PHP
    - cd $DEPLOYPATH && $PHP_BIN $COMPOSER_BIN install --no-dev --optimize-autoloader --no-interaction 2>&1

    # 5. Limpar caches
    - cd $DEPLOYPATH && $PHP_BIN artisan optimize:clear 2>&1

    # 6. Migrations
    - cd $DEPLOYPATH && $PHP_BIN artisan migrate --force 2>&1

    # 7. Cache de producao
    - cd $DEPLOYPATH && $PHP_BIN artisan optimize 2>&1

    # 8. Storage link
    - cd $DEPLOYPATH && $PHP_BIN artisan storage:link --relative 2>&1

    # 9. Permissoes
    - chmod -R 775 $DEPLOYPATH/storage
    - chmod -R 775 $DEPLOYPATH/bootstrap/cache
